#! /bin/zsh

ONE=`sysctl -n vm.loadavg | awk '{print $2}'`
TWO=`sysctl -n vm.loadavg | awk '{print $3}'`
THREE=`sysctl -n vm.loadavg | awk '{print $4}'`

printf "\xE2\x9A\xA1\xEF\xB8\x8E ${ONE}/${TWO}/${THREE}"
